version: '3.8'
#启动命令 docker compose -p zmbdphouse -f docker-compose-mid.yml up -d
services:
  zmbdphouse-admin:
    build:
      context: service/admin
    image: zmbdphouseprd/zmbdp-admin-service:1.0-SNAPSHOT
    container_name: zmbdphouse-admin-prd
    ports:
      - "18081:18081"
    environment:
      RUN_ENV: prd
      NACOS_ADDR: 你的云服务器1内网ip/你的虚拟机1内网ip:8854,你的云服务器1内网ip/你的虚拟机1内网ip:8856,你的云服务器2内网ip/你的虚拟机2内网ip:8858
      JAVA_OPTS: -Xmx256m -Dspring.cloud.nacos.discovery.ip=你的云服务器2内网ip/你的虚拟机2内网ip
    networks:
      zmbdphouse_network_prd:
  zmbdphouse-file:
    build:
      context: service/file
    ports:
      - "18082:18082"
    image: zmbdphouseprd/zmbdp-file-service:1.0-SNAPSHOT
    container_name: zmbdphouse-file-prd
    environment:
      RUN_ENV: prd
      NACOS_ADDR: 你的云服务器1内网ip/你的虚拟机1内网ip:8854,你的云服务器1内网ip/你的虚拟机1内网ip:8856,你的云服务器2内网ip/你的虚拟机2内网ip:8858
      JAVA_OPTS: -Xmx256m -Dspring.cloud.nacos.discovery.ip=你的云服务器2内网ip/你的虚拟机2内网ip
    networks:
      zmbdphouse_network_prd:
  zmbdphouse-gateway:
    build:
      context: service/gateway
    ports:
      - "18080:18080"
    image: zmbdphouseprd/zmbdp-gateway-service:1.0-SNAPSHOT
    container_name: zmbdphouse-gateway-prd
    environment:
      RUN_ENV: prd
      NACOS_ADDR: 你的云服务器1内网ip/你的虚拟机1内网ip:8854,你的云服务器1内网ip/你的虚拟机1内网ip:8856,你的云服务器2内网ip/你的虚拟机2内网ip:8858
      JAVA_OPTS: -Xmx256m -Dspring.cloud.nacos.discovery.ip=你的云服务器2内网ip/你的虚拟机2内网ip
    networks:
      zmbdphouse_network_prd:
  zmbdphouse-portal:
    build:
      context: service/portal
    ports:
      - "18083:18083"
    image: zmbdphouseprd/zmbdp-portal-service:1.0-SNAPSHOT
    container_name: zmbdphouse-portal-prd
    environment:
      RUN_ENV: prd
      NACOS_ADDR: 你的云服务器1内网ip/你的虚拟机1内网ip:8854,你的云服务器1内网ip/你的虚拟机1内网ip:8856,你的云服务器2内网ip/你的虚拟机2内网ip:8858
      JAVA_OPTS: -Xmx256m -Dspring.cloud.nacos.discovery.ip=你的云服务器2内网ip/你的虚拟机2内网ip
    networks:
      zmbdphouse_network_prd:
  zmbdphouse-chat:
    build:
      context: service/chat
    ports:
      - "18084:18084"
    image: zmbdphouseprd/zmbdp-chat-service:1.0-SNAPSHOT
    container_name: zmbdphouse-chat-prd
    environment:
      RUN_ENV: prd
      NACOS_ADDR: 192.168.100.233:8854,192.168.100.233:8856,192.168.100.235:8858
      JAVA_OPTS: -Xmx256m -Dspring.cloud.nacos.discovery.ip=192.168.100.233
    networks:
      zmbdphouse_network_prd:
networks:
  zmbdphouse_network_prd:
